global using System;
global using System.Collections.Generic;
global using SAP.Middleware.Connector;
global using Newtonsoft.Json.Linq;
global using GenericTypes.Responses;
global using GenericTypes.Constants;
global using QueryStructures.RFCStructures;
global using System.Linq;
global using GenericTypes.Languages;
global using System.Data;
global using RuntimeHelpers;
global using TableParsing = ParsingUtils.DataTables.Parsing;